### ISSUE TITLE
Restructure Console-Bank-App

### ISSUE THREAD

**Issue by jnyfah** [anene-ebube/Console-Bank-App#1]
- [x] Add gitignore file for the cmake build
- [x] arrange your files in folders and update you `CMakeLists.txt`, you can use this [Cmake examples](https://github.com/ttroy50/cmake-examples/tree/master/01-basic/B-hello-headers)
- [x] If your first goal is to welcomes the user to the bank app "winBank App" with a good welcome screen, then clears the console after the welcome message, you can simply do something like this 
```c++
void displayWelcomeScreen()
{
    // Set the console color to white on blue background
    HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    SetConsoleTextAttribute(hConsole, 15 );

    // Display the welcome message
    std::cout << "=====================================" << std::endl;
    std::cout << "  Welcome to the winBank App  " << std::endl;
    std::cout << "=====================================" << std::endl;

    // Wait for 3 seconds before clearing the console
    Sleep(3000);

    // Clear the console
    system("cls");
}
```

- [x]  Ask user for account number , save it in a variable

**Comment by ebubeanene** [comment]
Closed #1
